version: "3"
services:
    node-app:
        build: .
        ports:
            - "3333:3333"
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - PORT=3333
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
        # env_file:
            # - ./.env
        depends_on:
            - mongo
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - mongo-db:/data/db

volumes:
    mongo-db: