version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - network

  calcbp:
    build: ../BP_service
    networks:
      - network

  node-app:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3333
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    depends_on:
      - mongo
    networks:
      - network
    
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-db:/data/db
    networks:
      - network

volumes:
  mongo-db:

networks:
  network: {}
  